
[env]
TERM = "xterm-256color"

[window]
padding.x = 14
padding.y = 14
decorations = "Buttonless"
opacity = 0.9
blur = true
option_as_alt = "None"

[font]
size = 14

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[selection]
save_to_clipboard = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
working_directory = "None"
# see https://alacritty.org/config-alacritty.html
import = [    
    # Provide the path to the theme flavour you want below:
    "~/.config/alacritty/catppucin-theme/catppuccin-mocha.toml",
    # "~/.config/alacritty/alacritty-theme/dawnfox.toml"
]

[terminal]
shell.program = "/opt/homebrew/bin/bash"
shell.args = ["-l"]
